src/Form/Common/TagType.php
<?php

declare(strict_types=1);

namespace App\Form\Common;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TagType extends AbstractType
{
    public function getParent(): string
    {
        return TextType::class;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'label' => 'Tags',
            'attr' => [
                'placeholder' => 'Enter tags',
                'class' => 'form-control form-control-sm form-control-solid mb-2',
                'data-controller' => 'tagify',
            ]
        ]);
    }
}

templates/components/GalleryGlobalSidebarComponent.html.twig
<div{{ attributes.defaults({
    'class': 'w-100'
}) }}>
    <div class="d-flex flex-xl-row gap-1 gap-xl-2 align-items-center flex-row-fluid">
        <!--begin::Form-->
        <form class="w-100" autocomplete="off">
            {% import 'Admin/partials/macros.html.twig' as macros %}
            {{ macros.table_get_input_search("w-100") }}
        </form>
        <!--end::Form-->
        {% if this.hasAddNew %}
            <button type="button" class="btn btn-flex btn-sm btn-light-primary h-40px" data-action="live#action:prevent"
                    data-live-action-param="addNew"
            >
                <i class="ki-duotone ki-cross fs-2 p-0">
                    <span class="path1"></span>
                    <span class="path2"></span>
                </i></button>
        {% else %}
            <button type="button" class="btn btn-flex btn-sm btn-light-primary h-40px" data-action="live#action:prevent"
                    data-live-action-param="addNew"
            >
                <i class="ki-duotone ki-add-folder fs-2 p-0">
                    <span class="path1"></span>
                    <span class="path2"></span>
                </i></button>
        {% endif %}
    </div>
    <!--begin::List-->
    <div class="scroll-y me-n5 pe-5 h-200px h-lg-auto" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_header, #kt_app_header, #kt_toolbar, #kt_app_toolbar, #kt_footer, #kt_app_footer, #kt_chat_contacts_header" data-kt-scroll-wrappers="#kt_content, #kt_app_content, #kt_chat_contacts_body">
        {% if this.hasAddNew %}
            {{ form_start(form) }}
            {{ form_row(form.name) }}

            <button type="button" class="btn btn-sm btn-primary fs-7" data-action="live#action:prevent" data-live-action-param="saveNewGallery">Save</button>
            {{ form_end(form) }}
        {% endif %}
        {% for gallery in computed.data %}
            <!--begin::Item-->
            <div class="d-flex flex-stack py-4 ">
                <!--begin::Details-->
                <div class="d-flex align-items-center">
                    <span class="icon-wrapper">
                        <i class="ki-duotone ki-folder fs-2x text-muted me-4">
                            <span class="path1"></span>
                            <span class="path2"></span>
                        </i>
                    </span>
                    <a href="#" data-action="live#action:prevent" data-live-action-param="setGallery"
                       data-live-gallery-param="{{ gallery.id }}"
                       class="{{ this.gallery.id == gallery.id ? "text-primary": "text-gray-800"  }} text-hover-primary">{{ gallery.name }}</a>
                    <span class="badge badge-sm badge-circle badge-light-success">{{ gallery.countPictures }}</span>
                </div>
                <!--end::Details-->
                <!--begin::Lat seen-->
                <div class="d-flex flex-column align-items-end">
                    <span class="text-muted fs-7">{{ gallery.createdAt | date('d/m/Y H:i:a') }}</span>
                </div>
                <!--end::Lat seen-->
            </div>
            <!--end::Item-->
        {% endfor %}
    </div>
    <!--end::List-->
</div>

{% macro placeholder(props) %}
    <div class="w-100 h-150px d-flex justify-content-center align-items-center">
        <span class="fs-7 primary-hp fw-bold text-center">Loading.....</span>
    </div>
{% endmacro %}

templates/components/ListingItemLiveComponent.html.twig
<div{{ attributes }}>
    {% set content = block.content | json_decode %}
    {% if content.listingItem is defined and content.listingItem is not empty %}
        {% for item in content.listingItem %}
            {{ include(template) }}
        {% endfor %}
    {% endif %}
</div>

templates/components/TableBlockChildLiveComponent.html.twig
<div{{ attributes }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}

    <div class="d-flex flex-wrap flex-stack mb-6">
        {{ macros.table_get_input_search() }}
        <div class="d-flex my-2"></div>
    </div>

    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}

        {% block columns %}
            {{ macros.table_column_default("Order", 'text-start') }}
            {{ macros.table_column_default("Block Name", 'text-start') }}
            {{ macros.table_column_default("Type", 'text-start') }}
            {{ macros.table_column_default("CreatedAt", 'text-start') }}
            {{ macros.table_column_default("UpdatedAt", 'text-start') }}
        {% endblock %}

        {% block rows %}
            {% for item in computed.data %}
                    <tr class="py-3 align-middle border-bottom border-gray-300 fs-7">
                        <td class="action-column">
                                <a href="{{ path('app_admin_block_editchild', {'id': item.id}) }}" class="btn btn-icon btn-active-light-primary w-20px h-20px me-2">
                                <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Edit" data-bs-original-title="Edit">
                                    {{ macros.icon_edit() }}
                                </span>
                            </a>
                            <a href="{{ path('app_admin_block_preview', {'id': item.id}) }}" class="btn btn-icon btn-active-light-primary w-20px h-20px me-2">
                                <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Preview" data-bs-original-title="Preview">
                                    {{ macros.icon_eye() }}
                                </span>
                            </a>
                            <a href="#" class="btn btn-icon btn-active-light-primary w-20px h-20px me-2">
                                <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Delete" data-bs-original-title="Delete">
                                    {{ macros.icon_delete() }}
                                </span>
                            </a>
                        </td>
                        <td>1</td>
                        <td>{{ item.title }}</td>
                        <td>{{ item.type }}</td>
                        <td>{{ item.createdAt | date('d/m/Y H:i:a') }}</td>
                        <td>{{ item.updatedAt | date('d/m/Y H:i:a') }}</td>
                    </tr>
            {% endfor %}
        {% endblock %}
    {% endembed %}
</div>

templates/components/TableCategoryLiveComponent.html.twig
<div{{ attributes.defaults({
    'data-controller': 'core-table'
}) }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}
    <div class="d-flex flex-wrap flex-stack mb-6">
        <!--begin::Title-->
        {{ macros.table_get_input_search() }}
        <!--end::Title-->
        <!--begin::Controls-->
        <div class="d-flex my-2">

        </div>
        <!--end::Controls-->
    </div>
    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}
        {% import 'Admin/partials/setting/macros.html.twig' as SettingMacros %}
        {% block columns %}
            {{ macros.table_column_default("Title", 'text-start') }}
            {{ macros.table_column_default("Description", 'text-start') }}
            {% if type == article_type_recipe %}
                {{ macros.table_column_default("Category", 'text-start') }}
            {% endif %}
            {{ macros.table_column_default("Published", 'text-start') }}
            {{ macros.table_column_default("CreatedAt", 'text-start') }}
            {{ macros.table_column_default("UpdatedAt", 'text-start') }}
        {% endblock %}
        {% block rows %}
            {% for item in computed.data %}
                <tr class="py-3 align-middle  border-bottom border-gray-300 fs-7">
                    <td class="action-column">
                        <a href="{{ path('app_admin_category_edit', {'id': item.id, 'type': type }) }}"
                           data-amz-btn-open-modal
                           class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Edit" data-bs-original-title="Edit">
                                {{ macros.icon_edit() }}
                            </span>
                        </a>
                        <a href="#" data-amz-btn-remove
                           data-action="{{ path('app_admin_category_delete', {'id': item.id, 'type': type ,'_csrf_token': csrf_token('category-delete-'~ item.id) }) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Delete" data-bs-original-title="Delete">
                                {{ macros.icon_delete() }}
                            </span>
                        </a>
                    </td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.description ?? "No description" }}</td>
                    <td>{{ item.parent ? item.parent.title : "Not found" }}</td>
                    <td>{{ item.createdAt | date('d/m/Y H:i:a') }}</td>
                    <td>{{ item.updatedAt | date('d/m/Y H:i:a') }}</td>
                </tr>
            {% endfor %}
        {% endblock %}
    {% endembed %}
</div>

templates/components/TableContactLiveComponent.html.twig
<div{{ attributes }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}
    <div class="d-flex flex-wrap flex-stack mb-6">
        <!--begin::Title-->
        {{ macros.table_get_input_search() }}
        <!--end::Title-->
        <!--begin::Controls-->
        <div class="d-flex my-2">

        </div>
        <!--end::Controls-->
    </div>

    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}
        {% block columns %}
            {{ macros.table_column_default("Name") }}
            {{ macros.table_column_default("Phone") }}
            {{ macros.table_column_default("Email") }}
            {{ macros.table_column_default("Topic") }}
            {{ macros.table_column_default("Content") }}
            {{ macros.table_column_default("Status") }}
            {{ macros.table_column_default("Created At") }}
            {{ macros.table_column_default("Updated At") }}
        {% endblock %}

        {% block rows %}
            {% for contact in computed.data %}
                <tr class="align-middle border-bottom border-gray-300 fs-7 text-center">
                    <td>
                        {% if contact.status == 1 %}
                        <a href="{{ path('app_admin_contact_update',{'id':contact.id}) }}" class="btn btn-icon btn-active-light-primary me-1">
                            {{ macros.icon_edit() }}
                        </a>
                        {% endif %}
                        <a href="{{ path('app_admin_contact_delete', {'id': contact.id}) }}" class="btn btn-icon btn-active-light-danger" onclick="return confirm('Bạn có chắc chắn muốn xóa?')">
                            {{ macros.icon_delete() }}
                        </a>
                    </td>
                    <td>{{ contact.name }}</td>
                    <td>{{ contact.phone }}</td>
                    <td>{{ contact.email }}</td>
                    <td>{{ contact.topic }}</td>
                    <td>{{ contact.content }}</td>
                    <td>{{ contact.status ==0 ?'Đã xử lý':'Chưa xử lý'}}</td>
                    <td>{{ contact.createdAt|date('Y-m-d H:i') }}</td>
                    <td>{{ contact.updatedAt|date('Y-m-d H:i') }}</td>
                </tr>
            {% else %}
                <tr><td colspan="6">Không có dữ liệu cài đặt.</td></tr>
            {% endfor %}
        {% endblock %}
    {% endembed %}


</div>

templates/components/TableContactTopicLiveComponent.html.twig
<div{{ attributes.defaults({
    'data-controller': 'core-table'
}) }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}
    <div class="d-flex flex-wrap flex-stack mb-6">
        <!--begin::Title-->
        {{ macros.table_get_input_search() }}
        <!--end::Title-->
        <!--begin::Controls-->
        <div class="d-flex my-2">

        </div>
        <!--end::Controls-->
    </div>
    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}
        {% block columns %}
            {{ macros.table_column_default("TopicName", 'text-start') }}
            {{ macros.table_column_default("CreatedAt", 'text-start') }}
            {{ macros.table_column_default("UpdatedAt", 'text-start') }}
        {% endblock %}
        {% block rows %}
            {% for item in computed.data %}
                <tr class="py-3 align-middle  border-bottom border-gray-300 fs-7">
                    <td class="action-column">
                        <a href="{{ path('app_admin_contact_topic_edit', {'id': item.id}) }}"
                           data-amz-btn-open-modal
                           class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Edit" data-bs-original-title="Edit">
                                {{ macros.icon_edit() }}
                            </span>
                        </a>
                        <a href="#" data-amz-btn-remove
                           data-action="{{ path('app_admin_contact_topic_delete', {'id': item.id ,'_csrf_token': csrf_token('contact-topic-delete-'~ item.id) }) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Delete" data-bs-original-title="Delete">
                                {{ macros.icon_delete() }}
                            </span>
                        </a>
                    </td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.createdAt | date('d/m/Y H:i:a') }}</td>
                    <td>{{ item.updatedAt | date('d/m/Y H:i:a') }}</td>
                </tr>
            {% endfor %}
        {% endblock %}
    {% endembed %}
</div>

templates/components/TableDistributorComponent.html.twig
<div{{ attributes.defaults({
    'data-controller': 'core-table'
}) }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}
    <div class="d-flex flex-wrap flex-stack mb-6">
        <!--begin::Title-->
        {{ macros.table_get_input_search() }}
        <!--end::Title-->
        <!--begin::Controls-->
        <div class="d-flex my-2">

        </div>
        <!--end::Controls-->
    </div>
    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}
        {% block columns %}
            {{ macros.table_column_default("CompanyName", 'text-start') }}
            {{ macros.table_column_default("CompanyAddress", 'text-start') }}
            {{ macros.table_column_default("Phone", 'text-start') }}
            {{ macros.table_column_default("Address", 'text-start') }}
            {{ macros.table_column_default("WebLink", 'text-start') }}
            {{ macros.table_column_default("Products", 'text-start') }}
            {{ macros.table_column_default("CreatedAt", 'text-start') }}
            {{ macros.table_column_default("UpdatedAt", 'text-start') }}
        {% endblock %}
        {% block rows %}
            {% for item in computed.data %}
                <tr class="py-3 align-middle  border-bottom border-gray-300 fs-7">
                    <td class="action-column">
                        <a href="{{ path('app_admin_distributor_edit', {'id': item.id}) }}"
                           data-amz-btn-open-modal
                           class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Edit" data-bs-original-title="Edit">
                                {{ macros.icon_edit() }}
                            </span>
                        </a>
                        <a href="#" data-amz-btn-remove
                           data-action="{{ path('app_admin_distributor_delete', {'id': item.id ,'_csrf_token': csrf_token('distributor-delete-'~ item.id) }) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Delete" data-bs-original-title="Delete">
                                {{ macros.icon_delete() }}
                            </span>
                        </a>
                    </td>
                    <td>{{ item.companyName }}</td>
                    <td>{{ item.companyAddress }}</td>
                    <td>{{ item.phone }}</td>
                    <td>{{ item.email }}</td>
                    <td>
                        <a href="{{ item.webLink }}" target="_blank">{{ item.webLink }}</a>
                    </td>
                    <td>{{ item.products }}</td>
                    <td>{{ item.createdAt | date('d/m/Y H:i:a') }}</td>
                    <td>{{ item.updatedAt | date('d/m/Y H:i:a') }}</td>
                </tr>
            {% endfor %}
        {% endblock %}
    {% endembed %}
</div>

templates/components/TableManufacturerLiveComponent.html.twig
<div{{ attributes }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}
    <div class="d-flex flex-wrap flex-stack mb-6">
        <!--begin::Title-->
        {{ macros.table_get_input_search() }}
        <!--end::Title-->
        <!--begin::Controls-->
        <div class="d-flex my-2">

        </div>
        <!--end::Controls-->
    </div>

    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}
        {% block columns %}
            {{ macros.table_column_default("Name") }}
            {{ macros.table_column_default("Phone") }}
            {{ macros.table_column_default("Address") }}
            {{ macros.table_column_default("Product") }}
            {{ macros.table_column_default("Sort Order") }}
            {{ macros.table_column_default("URL") }}
            {{ macros.table_column_default("Created At") }}
        {% endblock %}


        {% block rows %}
            {% for manufacturer in computed.data %}
                <tr class="align-middle border-bottom border-gray-300 fs-7 text-center">
                    <td>
                        <a href="{{ path('app_admin_manufacturer_edit',{'id':manufacturer.id}) }}" data-amz-btn-open-modal class="btn btn-icon btn-active-light-primary me-1">
                            {{ macros.icon_edit() }}
                        </a>
                        <a href="{{ path('app_admin_manufacturer_delete', {'id': manufacturer.id}) }}" class="btn btn-icon btn-active-light-danger" onclick="return confirm('Bạn có chắc chắn muốn xóa?')">
                            {{ macros.icon_delete() }}
                        </a>
                    </td>
                    <td>{{ manufacturer.name }}</td>
                    <td>{{ manufacturer.phone }}</td>
                    <td>{{ manufacturer.address }}</td>
                    <td>{{ manufacturer.products|join(', ') }}</td>
                    <td>{{ manufacturer.urlWeb }}</td>
                    <td>{{ manufacturer.createdAt|date('Y-m-d H:i') }}</td>
                </tr>
            {% else %}
                <tr><td colspan="100%">Không có dữ liệu cài đặt.</td></tr>
            {% endfor %}
        {% endblock %}

    {% endembed %}


</div>

templates/components/TableMenuLiveComponent.html.twig
<div{{ attributes }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}
    <div class="d-flex flex-wrap flex-stack mb-6">
        <!--begin::Title-->
        {{ macros.table_get_input_search() }}
        <!--end::Title-->
        <!--begin::Controls-->
        <div class="d-flex my-2">

        </div>
        <!--end::Controls-->
    </div>
    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}
        {% block columns %}
            {{ macros.table_column_default("Author", 'text-start') }}
            {{ macros.table_column_default("Display", 'text-start') }}
            {{ macros.table_column_default("Menu Name", 'text-start') }}
            {{ macros.table_column_default("Position", 'text-start') }}
            {{ macros.table_column_default("CreatedAt", 'text-start') }}
            {{ macros.table_column_default("UpdatedAt",  'text-start') }}
        {% endblock %}
        {% block rows %}
            {% for item in computed.data %}
                <tr class="py-3 align-middle  border-bottom border-gray-300 fs-7">
                    <td class="action-column">
                        <a href="{{ path('app_admin_menu_edit', {'id': item.id}) }}"   data-amz-btn-open-modal class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Edit" data-bs-original-title="Edit">
                                {{ macros.icon_edit() }}
                            </span>
                        </a>
                        {% if type == menu_type_sub %}
                            <a href="{{ path('app_admin_menu_addchild', {'parentId': item.id}) }}"   data-amz-btn-open-modal class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Add child" data-bs-original-title="Add child">
                                  {{ macros.icon_add() }}
                            </span>
                            </a>
                        {% elseif type == menu_type_root %}
                            <a href="{{ path('app_admin_menu_child_index', {'parentId': item.id}) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Add child" data-bs-original-title="Add child">
                                  {{ macros.icon_add() }}
                            </span>
                            </a>
                        {% endif %}

                        <a href="#" data-amz-btn-remove
                           data-action="{{ path('app_admin_menu_delete', {'id': item.id, '_csrf_token': csrf_token('menu-delete-'~ item.id) }) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Delete" data-bs-original-title="Delete">
                                {{ macros.icon_delete() }}
                            </span>
                        </a>
                    </td>
                    <td>{{ item.author.username }}</td>
                    <td>{{ item.display }}</td>
                    <td>{{ item.name }}</td>
                    <td><span class="badge badge-primary fs-7">{{ item.position }}</span></td>
                    <td>{{ item.createdAt | date('d/m/Y H:i:a') }}</td>
                    <td>{{ item.updatedAt | date('d/m/Y H:i:a') }}</td>
                </tr>
                {% if type == menu_type_sub %}
                    {% if item.children is not empty %}
                        <tr>
                            <td colspan="1">
                            </td>
                            <td colspan="6">
                                <table class="table  table-row-dashed table-row-gray-500 gy-5 gs-5 mb-0">
                                    <thead>
                                    <tr class="fw-semibold fs-7 text-gray-800">
                                        <th scope="col">Action</th>
                                        <th scope="col">Child Name</th>
                                        <th scope="col">Url</th>
                                        <th scope="col">CreatedAt</th>
                                        <th scope="col">UpdatedAt</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for child in item.children %}
                                        <tr>
                                            <th scope="row">
                                                <a href="{{ path('app_admin_menu_edit', {'id': child.id}) }}"   data-amz-btn-open-modal class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Edit" data-bs-original-title="Edit">
                                                {{ macros.icon_edit() }}
                                            </span>
                                                </a>

                                                <a href="#" data-amz-btn-remove
                                                   data-action="{{ path('app_admin_menu_delete', {'id': child.id, '_csrf_token': csrf_token('menu-delete-'~ item.id) }) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                                                <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Delete" data-bs-original-title="Delete">
                                                    {{ macros.icon_delete() }}
                                                </span>
                                                </a>
                                            </th>
                                            <td>{{ child.name }}</td>
                                            <td>
                                                <a href="#">{{ absolute_url(child.url) }}</a>
                                            </td>
                                            <td>{{ child.createdAt | date('d/m/Y H:i:a') }}</td>
                                            <td>{{ child.updatedAt | date('d/m/Y H:i:a') }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endblock %}
    {% endembed %}
</div>

templates/components/TablePageLiveComponent.html.twig
<div{{ attributes }}>
    {% import 'Admin/partials/macros.html.twig' as macros %}
    <div class="d-flex flex-wrap flex-stack mb-6">
        <!--begin::Title-->
        {{ macros.table_get_input_search() }}
        <!--end::Title-->
        <!--begin::Controls-->
        <div class="d-flex my-2">

        </div>
        <!--end::Controls-->
    </div>
    {% embed 'Admin/partials/table.html.twig' %}
        {% import 'Admin/partials/macros.html.twig' as macros %}
        {% block columns %}
            {{ macros.table_column_default("Page Name", 'text-start') }}
            {{ macros.table_column_default("Language", 'text-start') }}
            {{ macros.table_column_default("CreatedAt", 'text-start') }}
            {{ macros.table_column_default("UpdatedAt",  'text-start') }}
        {% endblock %}
        {% block rows %}
            {% for item in computed.data %}

                <tr class="py-3 align-middle  border-bottom border-gray-300 fs-7">
                    <td class="action-column">
                        <a href="{{ path('app_admin_page_edit', {'id': item.id}) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Edit" data-bs-original-title="Edit">
                                {{ macros.icon_edit() }}
                            </span>
                        </a>
                        <a href="{{ path('app_admin_block_index', {'id': item.id}) }}" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">

                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Block" data-bs-original-title="Block">
                                 <i class="ki-duotone ki-arrow-two-diagonals fs-2">
                                        <span class="path1"></span>
                                        <span class="path2"></span>
                                        <span class="path3"></span>
                                        <span class="path4"></span>
                                        <span class="path5"></span>
                                    </i>
                            </span>
                        </a>
                        <a href="#" class="btn btn-icon btn-active-light-primary w-30px h-30px me-2">
                            <span data-bs-toggle="tooltip" data-bs-trigger="hover" aria-label="Delete" data-bs-original-title="Delete">
                                {{ macros.icon_delete() }}
                            </span>
                        </a>
                    </td>
                    <td>{{ item.name }}<br>
                        <a target="_blank" href="{{ absolute_url('/'~ item.post.slug ~'.html') }}">{{ absolute_url('/'~ item.post.slug ~'.html') }}</a>
                    </td>
                    <td>Vietnamese</td>
                    <td>{{ item.createdAt | date('d/m/Y H:i:a') }}</td>
                    <td>{{ item.updatedAt | date('d/m/Y H:i:a') }}</td>
                </tr>
            {% endfor %}
        {% endblock %}
    {% endembed %}
</div>